#ifndef TOUSCRUINO_HPP
#define TOUSCRUINO_HPP

#define TOUSCRUINO_PORT 	PB
#define TOUSCRUINO_CD 		21
#define TOUSCRUINO_WR 		22
#define TOUSCRUINO_RD 		23
#define TOUSCRUINO_CS 		0xFF
#define TOUSCRUINO_RESET 	0xFF

#define TOUSCRUINO_BACKLIGHT 5

#define TOUSCRUINO_XM	A6
#define TOUSCRUINO_XP	15
#define TOUSCRUINO_YM	14
#define TOUSCRUINO_YP	A7

#define TOUSCRUINO_PRESSURE_THRESHOLD 10
#define TOUSCRUINO_X_PLANE_RESISTANCE 300

#endif