#ifndef ARDURCT_LOCAL_CONFIG_H
#define ARDURCT_LOCAL_CONFIG_H

#include "../ArduRCT_Config.h"

#define LCD_BACKLIGHT_PIN 11

#define LCD_SCLK_PIN 3
#define LCD_SDIN_PIN 4
#define LCD_DC_PIN 5
#define LCD_RESET_PIN 6
#define LCD_SCE_GRAPHIC_PIN 7
#define LCD_SCE_TEXT_PIN 8

#define JOYSTICK_THROTTLE_PIN 2
#define JOYSTICK_YAW_PIN 3
#define JOYSTICK_PITCH_PIN 0
#define JOYSTICK_ROLL_PIN 1

#define BATTERY_PIN 6

#endif
